### ISSUE TITLE
[unrelated] comet quickstart should say `pip install comet-ml`, not `pip install comet_ml`?

### ISSUE THREAD

**Issue by WillDudley** [sherpan/comet-rl#2]

**Comment by Lothiraldan** [comment]
Hi @WillDudley thanks for the feedback. On pypi and with pip, the two are equivalent.

Given that we have also a Conda package named `comet_ml` where case do matter, we will likely keep the version with the underscore `pip install comet_ml`. It's also more consistent between the `pip install` call and the import `import comet_ml`.

Did you encountered a case where installed the package `comet_ml` didn't worked or did it caused some confusion?

**Comment by WillDudley** [comment]
Ah, sorry, I opened this issue to check it later myself - but thanks for responding!

I use an IDE GUI (pycharm) for my package mgmt and noticed there was no `comet_ml` explicitly listed on PyPi.
